CREATE TABLE `visit_summary` (
  `IDENTIFIER` bigint NOT NULL AUTO_INCREMENT,
  `SPEC_TYPE_SUMMARY_ID` bigint NOT NULL,
  `VISIT_CUSTOM_CLINICAL_DIAGNOSIS` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`IDENTIFIER`),
  KEY `IDX_VISIT_SUMMARY_SPEC_TYPE_SUMMARY_ID` (`SPEC_TYPE_SUMMARY_ID`),
  KEY `IDX_VISIT_SUMMARY_DIAGNOSIS` (`VISIT_CUSTOM_CLINICAL_DIAGNOSIS`),
  CONSTRAINT `FK_VISIT_SUMMARY_SPEC_TYPE_SUMMARY` FOREIGN KEY (`SPEC_TYPE_SUMMARY_ID`) REFERENCES `visit_specimen_type_summary` (`IDENTIFIER`)
)

CREATE TABLE `visit_specimen_type_summary` (
  `IDENTIFIER` bigint NOT NULL AUTO_INCREMENT,
  `VISIT_ID` bigint NOT NULL,
  `SPECIMEN_TYPE` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  `COUNT_OF_ALIQUOTS` int DEFAULT NULL,
  `collection_age` int DEFAULT NULL,
  PRIMARY KEY (`IDENTIFIER`),
  KEY `IDX_VSTS_VISIT_ID` (`VISIT_ID`),
  KEY `IDX_VSTS_SPECIMEN_TYPE` (`SPECIMEN_TYPE`),
  KEY `IDX_VSTS_COUNT_OF_ALIQUOTS` (`COUNT_OF_ALIQUOTS`),
  KEY `IDX_VSTS_COLLECTION_AGE` (`collection_age`),
  CONSTRAINT `FK_VSTS_VISIT_ID` FOREIGN KEY (`VISIT_ID`) REFERENCES `catissue_specimen_coll_group` (`IDENTIFIER`)
)

CREATE TABLE `sequencing_type_and_results_summary` (
  `IDENTIFIER` bigint NOT NULL AUTO_INCREMENT,
  `SPEC_TYPE_SUMMARY_ID` bigint NOT NULL,
  `SEQUENCING_TYPE_AND_RESULTS` varchar(255) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`IDENTIFIER`),
  KEY `IDX_STARS_SPEC_TYPE_SUMMARY_ID` (`SPEC_TYPE_SUMMARY_ID`),
  KEY `IDX_STARS_TYPE_AND_RESULTS` (`SEQUENCING_TYPE_AND_RESULTS`),
  CONSTRAINT `FK_STARS_SPEC_TYPE_SUMMARY` FOREIGN KEY (`SPEC_TYPE_SUMMARY_ID`) REFERENCES `visit_specimen_type_summary` (`IDENTIFIER`)
)
