CREATE TABLE `visit_summary` (
  `IDENTIFIER` bigint NOT NULL AUTO_INCREMENT,
  `SPEC_TYPE_SUMMARY_ID` bigint NOT NULL,
  `VISIT_CUSTOM_CLINICAL_DIAGNOSIS` varchar(255) COLLATE utf8mb3_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`IDENTIFIER`),
  KEY `IDX_VISIT_SUMMARY_SPEC_TYPE_SUMMARY_ID` (`SPEC_TYPE_SUMMARY_ID`),
  KEY `IDX_VISIT_SUMMARY_DIAGNOSIS` (`VISIT_CUSTOM_CLINICAL_DIAGNOSIS`),
  CONSTRAINT `FK_VISIT_SUMMARY_SPEC_TYPE_SUMMARY`
    FOREIGN KEY (`SPEC_TYPE_SUMMARY_ID`)
    REFERENCES `visit_specimen_type_summary` (`IDENTIFIER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

INSERT INTO visit_summary (
    SPEC_TYPE_SUMMARY_ID,
    VISIT_CUSTOM_CLINICAL_DIAGNOSIS
)
SELECT DISTINCT
    vsts.IDENTIFIER AS SPEC_TYPE_SUMMARY_ID,
    de.DE_A_3 AS VISIT_CUSTOM_CLINICAL_DIAGNOSIS
FROM catissue_specimen_coll_group visit
JOIN visit_specimen_type_summary vsts
    ON vsts.VISIT_ID = visit.IDENTIFIER
LEFT JOIN os_visit_extn_recs visit_ext
    ON visit_ext.VISIT_ID = visit.IDENTIFIER
    AND visit_ext.FORM_ID = 928
LEFT JOIN de_e_12200 de
    ON de.IDENTIFIER = visit_ext.RECORD_ID
WHERE visit.activity_status = 'Active'
  AND de.DE_A_3 IS NOT NULL;
